<?php
$title = 'Create Listing';
?>

<form action="/listings/create" method="post" class="outerDiv p-3 m-5 mx-auto">
    <div class="text-center">
        <h2>Welcome User (In Location)</h2>
        <h3>Please list an item</h3>
    </div>
    <div class="my-4 mb-3">
        <label for="inputTitle">Title</label>
        <input type="text" class="form-control" name="inputTitle" id="inputTitle" placeholder="Type here...">
    </div>
    <div class="my-4 mb-3 text-center d-flex justify-content-between">
        <img class="listCreateImage1" img src="" alt="Empty Image">
        <img class="listCreateImage2" img src="" alt="Empty Image">
        <img class="listCreateImage3" img src="" alt="Empty Image">
        <img class="listCreateImage4" img src="" alt="Empty Image">
        <img class="listCreateImage5" img src="" alt="Empty Image">
    </div>
    <div class="my-4 mb-3">
        <label for="description">Description</label>
        <textarea class="form-control" name="description" id="description" rows="4" placeholder="Type here..."></textarea>
    </div>
    <div class="grid-container-panel my-3 mb-3  d-flex justify-content-between">
        <div class="exchange-method-option">
            <table class="table table-borderless">
                <tbody>
                    <tr>
                        <td><input class="form-check-input me-1" type="radio" name="listingType" value="sell">Sell</td>
                        <td><input type="text" class="form-control" name="inputPrice" id="inputPrice" placeholder="£ Price"></td>
                    </tr>
                    <tr>
                        <td><input class="form-check-input me-1" type="radio" name="listingType" value="exchange">Exchange for</td>
                        <td><input type="text" class="form-control" name="inputItem" id="inputItem" placeholder="Item"></td>
                    </tr>
                    <tr>
                        <td><input class="form-check-input me-1" type="radio" name="listingType" value="giveaway">Giveaway</td>
                        <td><input class="form-check-input" type="checkbox" name="checkConf" id="checkConf">
                        <label class="form-check-label" for="checkConf">Please Confirm</label></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="create-categories">
            <label for="inputCategories" class="form-label"> Categories (Separate using commas)</label>
            <textarea class="form-control" id="inputCategories" placeholder="Tag1, Tag2, Tag3" rows="4"></textarea>
        </div>
    </div>
    <div class="my-4 mb-3 text-center">
        <button type="submit" class="btn btn-outline-danger">Submit Listing</button>
    </div>
</form>