<?php
$title = "Search page";
?>

<div class="grid-container-search mx-auto p-3 m-5">
    <div class="grid-filters">
        <div class="grid-filter-menu ">
            <div class="text-center">
                <strong>Filters:</strong>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="trade_selling" name="trade_selling" value=1>
                <label for="trade_selling">Selling</label><br>
                <input class="form-check-input" type="checkbox" id="trade_swapping" name="trade_swapping" value=2>
                <label for="trade_swapping">Swapping</label><br>
                <input class="form-check-input" type="checkbox" id="price_1" name="price_1" value=3>
                <label for="price_1">£0-£50</label><br>
                <input class="form-check-input" type="checkbox" id="price_2" name="price_2" value=4>
                <label id = "filter-label" for="price_2">£50-£100</label><br>
            </div>
            <div class="text-center">
                <button type="button" class="btn btn-danger">Submit</button>
            </div>
        </div>
    </div>
    <div class="grid-item">
        <div class="flex-container">
            <div>
                <img class="listing-image" src="">
            </div>
            <div class= "listing-description">
                <h4>Title</h4>
                <h5>This is an amazing item</h5>
                <h6>Seller name, Location</h6>
                <h4>Sold for £Price</h4>
            </div>
        </div>
    </div>
</div>




