<?php
/**
 * @var Listing $listings
 *
 */

use GroupThr3e\AJExchange\Models\Listing;

$title = "Search page";
?>
<div class="outerDiv search-grid-container mx-auto p-3 m-5">
    <div class="listing-filters-grid">
        <div class="listings-filters-menu ">
            <div class="mb-2">
                <strong>Filters:</strong>
            </div>
            <div class="form-check">
                <hr class="filter-seperation mt-2 mb-3"/>
                <h6>Exchange Method</h6>
                <input class="form-check-input" type="checkbox" id="trade_selling" name="trade[]" value="selling">
                <label for="trade_selling">Selling</label><br>
                <input class="form-check-input" type="checkbox" id="trade_exchange" name="trade[]" value="exchange">
                <label for="trade_exchange">Exchange</label><br>
                <input class="form-check-input" type="checkbox" id="trade_giveaway" name="trade[]" value="giveaway">
                <label for="trade_giveaway">Giveaway</label><br>
                <hr class="filter-seperation mt-2 mb-3"/>
                <h6>Price Range</h6>
                <input class="form-check-input" type="checkbox" id="price_1" name="price[]" value=3>
                <label for="price_1">£0-£50</label><br>
                <input class="form-check-input" type="checkbox" id="price_2" name="price[]" value=4>
                <label id = "filter-label" for="price_2">£50-£100</label><br>
                <input class="form-check-input" type="checkbox" id="price_3" name="price[]" value=5>
                <label id = "filter-label" for="price_3">£100+</label><br>
                <hr class="filter-seperation mt-2 mb-3"/>
                <h6>Categories</h6>
                <input class="form-check-input" type="checkbox" id="category_1" name="category[]" value=3>
                <label for="category_1">Category 1</label><br>
                <input class="form-check-input" type="checkbox" id="category_2" name="category[]" value=4>
                <label id = "category_2" for="price_2">Category 2</label><br>
                <input class="form-check-input" type="checkbox" id="category_3" name="category[]" value=5>
                <label id = "category_3" for="price_3">Category 3</label><br>
                <hr class="filter-seperation mt-2 mb-3"/>

            </div>
            <form class="mt-4">
                <button type="button" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <div class="listing-search-results">
        <?php if(!empty($listings)):?>
         <?php foreach($listings as $listing): ?>
            <div class="listing-search-result">
                <div>
                    <a href="<?=$listing->getListingID()?>"><img class="listing-search-result-image" alt="" src="https://dummyimage.com/200x200/000000/fff.jpg&text=Listing"</a>
                </div>
                <div class= "listing-search-result-description">
                        <a href="<?=$listing->getListingID()?>"><h3><?= $listing->getListingName()?></h3></a>
                        <h5>Description: <?=$listing->getDescription()?></h5>
                        <?php if($listing->getType()=='sell'): ?>
                            <h6>Price: £<?= $listing->getPrice() ?> </h6>
                        <?php elseif($listing->getType()=='exchange'): ?>
                            <h6>Exchange for: <?= $listing ->getDesiredItem() ?></h6>
                        <?php elseif($listing->getType()=='giveaway'): ?>
                            <h6>Giving away</h6>
                        <?php endif; ?>
                        <h6>Seller name: <?= $listing->getUser()->getFullName()?></h6>
                        <h6>Location: <?= $listing->getUser()->getOffice()->getAddress()?></h6>
                </div>
            </div>
         <?php endforeach; ?>
        <?php else:?>
            <div class="text-center listing-search-result">
                <h3>No results</h3>
            </div>
        <?php endif;?>
    </div>
</div>



