<?php
$title = "Search page";
?>

<div class="my-5">

    <div class="container">
        search results for:
    </div>

    <div class="grid-container">
        <div class="grid-filters">

            <div class="grid-filter-menu ">
                <strong>Trade Methods:</strong>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="trade_selling" name="trade_selling" value="honk"> Selling<br>
                    <input class="form-check-input" type="checkbox" id="trade_swapping" name="trade_swapping" value="bonk"> Swapping<br>
                    <input class="form-check-input" type="checkbox" id="price_1" name="price_1" value="honk">£0 to £100<br>
                    <input class="form-check-input" type="checkbox" id="price_2" name="price_2" value="bonk">£100 to £200<br>

                    <button type="button" class="btn btn-danger">Danger</button>
                </div>
            </div>





        </div>
        <div class="grid-item">
            <div class="flex-container">
                <div>
                    <img class="listing-image" img src="">
                </div>
                <div>
                    This is an amazing item that needs love
                </div>
            </div>

        </div>