<?php
$title = 'listing';
?>

<div class="listing-grid-container my-5 listing-grid-design mx-auto">
    <div class="view-main-image listing-grid-design">
        <img class="mainImage h-100 w-100" src="" alt="">
    </div>
    <div class="view-item-description listing-grid-design">
        <h6>Seller name, Location</h6>
        <div>
            <h4>Title</h4>
        </div>
    </div>
    <div class="view-interact-item listing-grid-design">
        <h6>Sold for £PRICE</h6>
        <button type="submit"  class="btn btn-primary w-100 mt-4">Submit</button>
    </div>
    <div class="view-extra-images listing-grid-design d-flex flex-column gap-2">
        <img class="extraImage" src="" alt="">
        <img class="extraImage" src="" alt="">
        <img class="extraImage" src="" alt="">
        <img class="extraImage" src="" alt="">
    </div>
    <div class="view-about listing-grid-design">About Section</div>
</div>