<?php
/**
 * @var View $this
 * @var Listing $listing
 */

use GroupThr3e\AJExchange\Constants\ApprovalStatus;
use GroupThr3e\AJExchange\Models\Listing;
use GroupThr3e\AJExchange\Util\Auth;
use GroupThr3e\AJExchange\Util\View;

$title = 'listing';
$user = Auth::getAuthManager()->getUser();
?>

<div class="view-listing-grid-container my-5 listing-grid-design mx-auto">
    <div class="view-listing-main-image-container listing-grid-design">
        <img class="view-listing-main-image w-100" src="<?= $this->listingImage($listing->getImageUrls()[0]) ?>" alt="">
    </div>
    <div class="view-listing-header listing-grid-design">
        <div>
            <h1><?= htmlspecialchars($listing->getListingName()) ?></h1>
        </div>
        <div><h6><?= $listing->getUser()->getOffice()->getAddress() ?> Office</h6></div>
    </div>
    <div class="view-listing-interact listing-grid-design">
        <?php if($listing->getType()=='sell'): ?>
        <h4 class="zero-margin">
            <?= $listing->getUser()->getFullName() ?>
            <?= $listing->getOrderId() === null ? 'is selling' : 'had sold' ?> for:
        </h4>
        <h4><span class="emphasise-item-text">£<?= htmlspecialchars($listing->getPrice()) ?></h4>
        <?php if ($listing->getCharity() !== null): ?>
        <h4>Proceeds go to <?= $listing->getCharity()->getCharityName() ?></h4>
        <?php endif; ?>
        <?php elseif($listing->getType()=='exchange'): ?>
        <h4 class="zero-margin">
            <?= $listing->getUser()->getFullName() ?>
            <?= $listing->getOrderId() === null ? 'Is exchanging' : 'Was exchanged' ?> for:
        </h4>
        <h4><span class="emphasise-item-text"><?= htmlspecialchars($listing->getDesiredItem()) ?></span>
        </h4>
        <?php elseif($listing->getType()=='giveaway'): ?>
        <h4>
            <?= $listing->getUser()->getFullName() ?>
            <?= $listing->getOrderId() === null ? 'Is giving' : 'Has given' ?> away
        </h4>
        <?php endif; ?>
        <?php if ($listing->getApprovalStatus() === ApprovalStatus::APPROVED && $listing->getUserId() !== $user->getUserId() && $listing->getOrderId() === null): ?>
        <form class="m-4" action="/listings/<?= $listing->getListingId() ?>/order" method="post">
            <button type="submit" class="btn btn-primary btn-secondary w-100 mt-4">Order</button>
        </form>
        <?php elseif ($listing->getApprovalStatus() === ApprovalStatus::PENDING && $user->getRole() === 'admin' && $listing->getOrderId() === null): ?>
        <div class="d-flex gap-2 mt-4">
            <form class="m-0" action="/listings/<?= $listing->getListingId() ?>/setApproval" method="post">
                <input type="hidden" name="approvalStatus" value="<?= ApprovalStatus::APPROVED ?>">
                <button type="submit" class="btn btn-primary btn-secondary ">Approve</button>
            </form>
            <form class="m-0" action="/listings/<?= $listing->getListingId() ?>/setApproval" method="post">
                <input type="hidden" name="approvalStatus" value="<?= ApprovalStatus::DENIED ?>">
                <button type="submit" class="btn btn-primary btn-secondary ">Deny</button>
            </form>
        </div>
        <?php elseif ($listing->getApprovalStatus() !== ApprovalStatus::APPROVED && $listing->getUserId() === $user->getUserId()): ?>
        <h3 class="mt-4">Approval Status: <?= $listing->getApprovalStatus() ?></h3>
        <?php endif; ?>
        <h4 class="mt-3">Tags:</h4>
        <div class="home-welcome list-div text-center view-listing-tags">
            <ul class="tag-list home-list-design list-unstyled">
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 1</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 2</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 3</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 4</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 5</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 6</a></li>
                <li class="tag-list"><a href="javascript:void(0)" class="h4 d-block">Category 7</a></li>
            </ul>
        </div>
    </div>
    <div class="view-listing-extra-images listing-grid-design d-flex flex-column gap-2">
        <?php foreach ($listing->getImageUrls() as $image): ?>
        <img class="view-listing-extra-image" src="<?= $this->listingImage($image) ?>" alt="">
        <?php endforeach; ?>
    </div>
    <div class="view-listing-description listing-grid-design view-listing-description-box text-overflow">
        <h4 class="view-listing-description-title">Description:</h4>
        <div><p><?= htmlspecialchars($listing->getDescription()) ?></p></div>
    </div>
</div>
