<?php
/**
 * @var string $title the title of the page
 * @var string $content the main content to display in the page body
 */

use GroupThr3e\AJExchange\Util\Auth;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="/public/ajbell_logo.png">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid text-light px-4">
            <div class="navbar-start-content">
                <a href="/" class="navbar-brand text-light">AJExchange</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler-target" aria-controls="navbar-toggler-target" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <?php if(Auth::getAuthManager()->getUser() !== null): ?>
            <div class="collapse navbar-collapse mt-4 mb-2 my-lg-0" id="navbar-toggler-target">
                <form action="/listings/search" method="get" class="d-flex my-lg-0 mb-3 mx-5 flex-grow-1" role="search">
                    <input name="query" class="form-control me-2 flex-grow-1" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light btn-navbar" type="submit">Search</button>
                </form>
                <h6 class="navbar-brand user-navbar">Current user: <?= Auth::getAuthManager()->getUser()->getFullName() ?></h6>
                <div class="navbar-end-content d-flex">
                    <div class="flex-grow-1"></div>
                    <form action="/users/logout" method="post" class="mb-0">
                        <button type="submit" class="btn btn-outline-light btn-navbar">Logout</button>
                    </form>
                </div>
            </div>
            <?php endif ?>
        </div>
    </nav>
    <div><?= $content ?></div>
    <footer>
        <div class="footer-content">
            <h3><a href="/">AJExchange</a></h3>
            <p>AJBell's Exclusive Market Place. At AJ Bell, we recognise the importance of societal action to reduce
                global emissions and are committed to playing our part and further support sustainability. </p>
            <a href="https://www.ajbell.co.uk">
                <img class="footer-logo" width="150" src="https://www.ajbell.co.uk/sites/all/themes/ajbyi_patternlab/logo.png" alt="AjBell Logo"></a>
            <ul class="socials">
                <li> <a href="https://www.youtube.com/channel/UCHcaVkNvsO6sLm-TxIwMnQw"><i class="fa fa-youtube"></i> </a> </li>
                <li> <a href="https://twitter.com/ajbell"><i class="fa fa-twitter"></i></a></li>
                <li> <a href="https://www.linkedin.com/company/ajbell/"><i class="fa fa-linkedin-square"></i> </a> </li>
                <li> <a href="https://www.facebook.com/AJBell"><i class="fa fa-facebook"></i> </a> </li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p>Built & Designed by: </p>
            <span>
                <a href="https://www.linkedin.com/in/george-wilson-aa76591a4/">George Wilson</a>,a
                <a href="https://www.linkedin.com/in/jakub-przysiwek/">Jakub Przysiwek</a>,
                <a href="https://www.linkedin.com/in/jacobhowles/">Jacob Howles</a>,
                <a href="https://www.linkedin.com/in/hassan-ali-572011245/">Hassan Ali</a>,
                <a href="https://www.linkedin.com/in/mafi-hossin/">Mafi Hossin</a>
            </span>
        </div>
    </footer>

    <script src="/public/js/script.js"></script>
    <script src="/public/js/bootstrap.bundle.js"></script>
</body>
</html>