<?php
/**
 * @var string $title the title of the page
 * @var string $content the main content to display in the page body
 */
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
</head>
<body>
    <div><?= $content ?></div>

    <script src="/js/bootstrap.bundle.js"></script>
</body>
</html>