<?php
/**
 * @var string $title the title of the page
 * @var string $content the main content to display in the page body
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/style.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid text-light px-4">
            <div class="navbar-start-content">
                <a href="/" class="navbar-brand text-light">AJExchange</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler-target" aria-controls="navbar-toggler-target" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mt-4 mb-2 my-lg-0" id="navbar-toggler-target">
                <form action="/listings/search" method="get" class="d-flex my-lg-0 mb-3 mx-5 flex-grow-1" role="search">
                    <input name="query" class="form-control me-2 flex-grow-1" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light btn-navbar" type="submit">Search</button>
                </form>
                <div class="navbar-end-content d-flex">
                    <div class="flex-grow-1"></div>
                    <form action="/users/logout" method="post" class="mb-0">
                        <button type="submit" class="btn btn-outline-light btn-navbar">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <div><?= $content ?></div>

    <script src="/public/js/script.js"></script>
    <script src="/public/js/bootstrap.bundle.js"></script>
</body>
</html>