<?php

use GroupThr3e\AJExchange\Models\HomepageData;

/**
 * @var HomepageData $data
 */

$title = 'index';
?>
<div class="outerDiv home-grid-design p-2 m-3 mx-auto">
    <div class="home-page-banner">
        <figure class="text-over-banner"><img class="banner-image" src="" alt=""><figcaption class = "banner-fig">Inspirational quote</figcaption></figure>
    </div>
    <div class="home-grid-container my-4">
        <div>
            <h5 class="home-image-titles">Recent sales</h5>
            <div class="view-extra-home-images home-grid-design d-flex flex-row gap-5 my-2 text-center">
                <?php foreach($data->recentSales as $recentSale): ?>
                <div class="home-image-containers">
                    <img class="home-images" src="" alt="">
                    <h5 class="home-image-descriptions"><?= $recentSale->getListingName() ?></h5>
                </div>
                <?php endforeach; ?>
            </div>
            <h5  class="home-image-titles">Recent exchanges</h5>
            <div class="view-extra-home-images home-grid-design d-flex flex-row gap-5 my-2">
                <?php foreach($data->recentExchanges as $recentExchange): ?>
                <div class="home-image-containers">
                    <img class="home-images" src="" alt="">
                    <h5 class="home-image-descriptions"><?= $recentExchange->getListingName() ?></h5>
                </div>
                <?php endforeach; ?>
            </div>
            <h5  class="home-image-titles">Recent giveaways</h5>
            <div class="view-extra-home-images home-grid-design d-flex flex-row gap-5 my-2">
                <?php foreach($data->recentGiveaways as $recentGiveaway): ?>
                <div class="home-image-containers">
                    <img class="home-images" src="" alt="">
                    <h5 class="home-image-descriptions"><?= $recentGiveaway->getListingName() ?></h5>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div>
            <div class="py-3 home-grid-design home-logo-misc">
                <h2 class="home-welcome">Welcome, User</h2>
                <h4 class="home-welcome">(Location)</h4>
                <div class="home-logo-container">
                    <img class="home-logos my-4" src="" alt="">
                    <h5 class="home-logo-descriptions">List Item</h5>
                </div>
                <div class="home-logo-container">
                    <img class="home-logos" src="" alt="">
                    <h5 class="home-logo-descriptions">Log out</h5>
                </div>
            </div>
            <div class="py-2 home-grid-design home-image-misc">
                <h2 class="home-welcome">Categories</h2>
                <div class="home-welcome">
                    <ul style="list-style-type:none;" class="home-list">
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 1</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 2</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 3</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 4</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 5</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 6</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 7</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 8</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 9</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>