<?php

use GroupThr3e\AJExchange\Models\HomepageData;
use GroupThr3e\AJExchange\Util\Auth;
use GroupThr3e\AJExchange\Util\View;

/**
 * @var View $this
 * @var HomepageData $data
 */

$title = 'AJExchange';
?>
<div class="outerDiv home-grid-design p-2 m-3 mx-auto">
    <div class="home-grid-container">
        <div>
            <h1 class="home-main-title">Recent Listings</h1>
            <hr class="filter-separation mt-2 mb-3"/>
            <h5 class="home-image-titles d-inline-block">Sales</h5><h5 class="home-view-more d-inline-block search-link-style"><a href="/listings/search?query=&type=sell">View all sales</a></h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentSales as $recentSale): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentSale->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentSale->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <a href="/listings/<?= $recentSale->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentSale->getListingName()) ?></a>
                    <a href="/listings/<?= $recentSale->getListingId() ?>" class="home-image-descriptions-container">£<?= htmlspecialchars($recentSale->getPrice()) ?></a>
                </div>
                <?php endforeach; ?>
            </div>
            <hr class="filter-separation mt-2 mb-3"/>
            <h5 class="home-image-titles d-inline-block">Exchanges</h5><h5 class="home-view-more d-inline-block search-link-style"><a href="/listings/search?query=&type=exchange">View all exchanges</a></h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentExchanges as $recentExchange): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentExchange->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentExchange->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <div class="home-image-descriptions-container">
                        <a href="/listings/<?= $recentExchange->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentExchange->getListingName()) ?></a>
                        <a href="/listings/<?= $recentExchange->getListingId() ?>" class="home-image-descriptions-container">Wants <?= htmlspecialchars($recentExchange->getDesiredItem()) ?></a>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <hr class="filter-separation mt-2 mb-3"/>
            <h5 class="home-image-titles d-inline-block">Giveaways</h5><h5 class="home-view-more d-inline-block search-link-style"><a href="/listings/search?query=&type=giveaway">View all giveaways</a></h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentGiveaways as $recentGiveaway): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentGiveaway->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentGiveaway->getListingName()) ?></a>
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>" class="home-image-descriptions-container">Free</a>
                </div>
                <?php endforeach; ?>
            </div>
            <hr class="filter-separation mt-2 mb-3"/>
        </div>
        <div class="index-control-box">
            <div class="py-3 home-logo-misc search-description-background">
                <div class="home-logo-container">
                    <a class="search-link-style" href="/listings/search"><button class="btn btn-outline-danger button-box-size">View all listings</button></a>
                </div>
                <div class="home-logo-container button-box-size">
                    <a class="search-link-style" href="/users/my/listings"><button class="btn btn-outline-danger  button-box-size">View your listings</button></a>
                </div>
                <div class="home-logo-container button-box-size">
                    <a class="search-link-style" href="/listings/create"><button class="btn btn-outline-danger  button-box-size">List an item</button></a>
                </div>
                <?php if(Auth::getAuthManager()->getUser()->getRole() == 'admin'): ?>
                <div class="home-logo-container button-box-size">
                    <a class="search-link-style" href="/listings/adminControls"><button class="btn btn-outline-danger  button-box-size">Admin Controls</button></a>
                </div>
                <?php endif; ?>
                <div class="home-logo-container button-box-size">
                    <a class="search-link-style" href="/users/my/orders"><button class="btn btn-outline-danger  button-box-size">View your orders</button></a>
                </div>
            </div>
            <div class="py-3 home-logo-misc search-description-background">
                <?php foreach ($data->tags as $tag): ?>
                <div class="home-logo-container">
                    <a class="search-link-style" href="/listings/search?tags[]=<?= $tag->getTag() ?>"><button class="btn btn-outline-login button-box-size"><?= $tag->getTag() ?></button></a>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>