<?php

use GroupThr3e\AJExchange\Models\HomepageData;
use GroupThr3e\AJExchange\Util\Auth;
use GroupThr3e\AJExchange\Util\View;

/**
 * @var View $this
 * @var HomepageData $data
 */

$title = 'AJExchange';
?>
<div class="outerDiv home-grid-design p-2 m-3 mx-auto">
    <h1>Recent Listings</h1>
    <div class="home-grid-container my-4">
        <div>
            <h5 class="home-image-titles">Sales</h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentSales as $recentSale): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentSale->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentSale->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <a href="/listings/<?= $recentSale->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentSale->getListingName()) ?></a>
                    <a href="/listings/<?= $recentSale->getListingId() ?>" class="home-image-descriptions-container">£<?= htmlspecialchars($recentSale->getPrice()) ?></a>
                </div>
                <?php endforeach; ?>
            </div>
            <h5  class="home-image-titles">Exchanges</h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentExchanges as $recentExchange): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentExchange->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentExchange->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <div class="home-image-descriptions-container">
                        <a href="/listings/<?= $recentExchange->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentExchange->getListingName()) ?></a>
                        <a href="/listings/<?= $recentExchange->getListingId() ?>" class="home-image-descriptions-container">Wants: <?= htmlspecialchars($recentExchange->getDesiredItem()) ?></a>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <h5  class="home-image-titles">Giveaways</h5>
            <div class="view-extra-home-images gap-3 text-center search-link-style">
                <?php foreach($data->recentGiveaways as $recentGiveaway): ?>
                <div class="home-image-containers">
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>">
                        <img class="home-images" src="<?= $this->listingImage($recentGiveaway->getImageUrls()[0]) ?>" alt="">
                    </a>
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>" class="home-image-descriptions h5"><?= htmlspecialchars($recentGiveaway->getListingName()) ?></a>
                    <a href="/listings/<?= $recentGiveaway->getListingId() ?>" class="home-image-descriptions-container">Free</a>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="index-control-box">
            <div class="py-3 home-grid-design home-logo-misc home-welcome-design">
                <h2 class="home-welcome white-design-text">Welcome, </h2>
                <h2 class="home-welcome white-design-text"><?= Auth::getAuthManager()->getUser()->getFullName() ?></h2>
                <h4 class="home-welcome white-design-text"><?= Auth::getAuthManager()->getUser()->getOffice()->getOfficeName() ?></h4>
                <div class="home-logo-container">
                    <h5 class="home-logo-descriptions white-design-text"><a class="text-light" href="/listings/search">View all listings</a></h5>
                </div>
                <div class="home-logo-container">
                    <h5 class="home-logo-descriptions white-design-text"><a class="text-light" href="/users/my/listings">View your listings</a></h5>
                </div>
                <div class="home-logo-container">
                    <h5 class="home-logo-descriptions white-design-text"><a class="text-light" href="/listings/create">List Item</a></h5>
                </div>
                <?php if(Auth::getAuthManager()->getUser()->getRole() == 'admin'): ?>
                <div class="home-logo-container">
                    <h5 class="home-logo-descriptions white-design-text"><a class="text-light" href="/listings/adminControls">Admin Controls</a></h5>
                </div>
                <?php endif; ?>
                <div class="home-logo-container">
                    <h5 class="home-logo-descriptions white-design-text"><a class="text-light" href="/users/my/orders">View your orders</a></h5>
                </div>
            </div>
            <div class="py-2 home-grid-design home-image-misc categories-color">
                <h2 style="color: white" class="home-welcome">Categories</h2>
                <div class="home-welcome list-div text-center">
                    <ul style="list-style-type:none; padding: 0;" class="home-list home-list-design">
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 1</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 2</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 3</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 4</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 5</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 6</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 7</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 8</a></li>
                        <li class="home-list"><a href="javascript:void(0)" class="h4 d-block">Category 9</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>