<?php
/**
 * @var View $this
 * @var Listing[] $listings
 * @var string $approvalStatus
 */

use GroupThr3e\AJExchange\Constants\ApprovalStatus;
use GroupThr3e\AJExchange\Models\Listing;
use GroupThr3e\AJExchange\Util\Auth;
use GroupThr3e\AJExchange\Util\View;

$title = "My listings";
?>

<div class="mx-auto search-title-div"><h5 class="search-title">Welcome,  <?= Auth::getAuthManager()->getUser()->getFullName() ?>, this is your listing history:</h5></div>
<div class="outerDiv search-grid-container mx-auto search-margin search-padding">
    <div class="listing-filters-grid">
        <form class="listings-filters-menu search-padding">
            <h6 class="filter-title">Filters:</h6>
            <div class="form-check">
                <input class="form-check-input" type="radio" id="to_approve" name="approvalStatus"
                       value="<?= ApprovalStatus::PENDING ?>" <?= $approvalStatus === ApprovalStatus::PENDING ? 'checked': '' ?>>
                <label for="to_approve">Pending</label><br>
                <input class="form-check-input" type="radio" id="approved" name="approvalStatus"
                       value="<?= ApprovalStatus::APPROVED ?>" <?= $approvalStatus === ApprovalStatus::APPROVED ? 'checked': '' ?>>
                <label for="approved">Approved</label><br>
                <input class="form-check-input" type="radio" id="declined" name="approvalStatus"
                       value="<?= ApprovalStatus::DENIED ?>" <?= $approvalStatus === ApprovalStatus::DENIED ? 'checked' : '' ?>>
                <label for="declined">Denied</label><br>
            </div>
            <hr class="filter-separation mt-2 mb-3"/>
            <button type="submit" class="btn btn-outline-danger" value="Submit">Apply</button>
        </form>
    </div>
    <div class="mobile-search-offcanvas">
        <a class="btn btn-primary w-100" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
            Filters
        </a>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasExampleLabel">Filters</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <div class="mobile-listing-filters-grid">
                    <form class="offset-listings-filters-menu search-padding">
                        <h6 class="filter-title">Filters:</h6>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" id="to_approve" name="approvalStatus"
                                   value="<?= ApprovalStatus::PENDING ?>" <?= $approvalStatus === ApprovalStatus::PENDING ? 'checked': '' ?>>
                            <label for="to_approve">Pending</label><br>
                            <input class="form-check-input" type="radio" id="approved" name="approvalStatus"
                                   value="<?= ApprovalStatus::APPROVED ?>" <?= $approvalStatus === ApprovalStatus::APPROVED ? 'checked': '' ?>>
                            <label for="approved">Approved</label><br>
                            <input class="form-check-input" type="radio" id="declined" name="approvalStatus"
                                   value="<?= ApprovalStatus::DENIED ?>" <?= $approvalStatus === ApprovalStatus::DENIED ? 'checked' : '' ?>>
                            <label for="declined">Denied</label><br>
                        </div>
                        <hr class="filter-separation mt-2 mb-3"/>
                        <button type="submit" class="btn btn-outline-danger" value="Submit">Apply</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="listing-search-results search-padding">
        <?php if(empty($listings)): ?>
            <h3 class="admin-welcome">No listings with specified filter found in history</h3>
        <?php else: ?>
        <?php foreach($listings as $listing): ?>
            <div class="listing-search-result search-description-background">
                <div class="search-description-image">
                    <a href="/listings/<?= $listing->getListingID() ?>">
                    <img class="listing-search-result-image" alt="" src="<?= $this->listingImage($listing->getImageUrls()[0]) ?>">
                </a>
                </div>
                <div class= "listing-search-result-description search-link-style text-overflow">
                    <a class="search-link-style" href="/listings/<?= $listing->getListingID() ?>"><h4><?= htmlspecialchars($listing->getListingName()) ?></h4></a>
                    <h6 class="search-description-style"><?= $listing->getUser()->getFullName() ?>, <?= $listing->getUser()->getOffice()->getOfficeName() ?></h6>
                    <?php if($listing->getType()=='sell'): ?>
                    <h6><span class="search-description-style">Selling for: </span></h6><h3>£<?= htmlspecialchars($listing->getPrice()) ?></h3>
                        <?php if ($listing->getCharity() !== null): ?>
                            <h6>Proceeds go to <?= $listing->getCharity()->getCharityName() ?></h6>
                        <?php endif; ?>
                    <?php elseif($listing->getType()=='exchange'): ?>
                        <h6><span class="search-description-style">Exchanging for: </span></h6><h3><?= htmlspecialchars($listing->getDesiredItem()) ?></h3>
                    <?php elseif($listing->getType()=='giveaway'): ?>
                        <h3>Giving away</span></h3>
                    <?php endif; ?>
                    <h6><?= htmlspecialchars($listing->getDescription()) ?></h6>
                    <?php if($listing->getApprovalStatus() == ApprovalStatus::APPROVED): ?>
                        <h4>Status: <span class="capitalise" style="color: green"><?= htmlspecialchars($listing->getApprovalStatus()) ?></span></h4>
                    <?php elseif($listing->getApprovalStatus() == ApprovalStatus::DENIED): ?>
                        <h4>Status: <span class="capitalise" style="color: orange"><?= htmlspecialchars($listing->getApprovalStatus()) ?></span></h4>
                    <?php elseif($listing->getApprovalStatus() == ApprovalStatus::PENDING): ?>
                        <h4>Status: <span class="capitalise" style="color: blue"><?= htmlspecialchars($listing->getApprovalStatus()) ?></span></h4>
                    <?php endif; ?>
                </div>
                <h6>You listed this on <?= htmlspecialchars($listing->getDateListed()) ?></h6>
            </div>
        <?php endforeach; ?>
        <?php endif ?>
    </div>
</div>
