<?php
$title = 'login';
?>

<div class="outerDiv text-center p-4 m-5 mx-auto">

    <form method="post"></form>
            <div class="mb-3">
                <div id="loginIntro" class="form-text">Log into the marketplace</div>
                <label for=inputEmail" class="form-label"> Email Address:</label>
                <input type="email" class="form-control" name="InputEmail" aria-describedby="emailHelp" placeholder="example@123.co.uk">
            </div>
            <div class="mb-3">
                <label for=inputPassword" class="form-label"> Password:</label>
                <input type="password" class="form-control" name="InputPassword">
            </div>
        <button type="submit"  class="btn btn-primary w-100 mt-4"> Log in</button>
    </form>

</div>