<?php
$title = 'login';
?>

<div class="createOuterDiv text-center p-4 m-5 mx-auto">
    <form action="/users/login" method="post">
            <div class="mb-3">
                <div id="loginIntro" class="form-text">Log into the marketplace</div>
                <label for="inputEmail" class="form-label"> Email Address:</label>
                <input type="email" class="form-control" name="inputEmail" id="inputEmail" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="inputPassword" class="form-label"> Password:</label>
                <input type="password" class="form-control" name="inputPassword" id="inputPassword">
            </div>
        <button type="submit"  class="btn btn-primary w-100 mt-4"> Log in</button>
    </form>
</div>